In [152]:
#Uniform Distribution(Continuous)

import numpy as np
data = np.random.uniform(0, 1, (2, 3))
print(data)

[[0.38661429 0.86531084 0.00641966]
 [0.7586462  0.6595859  0.07346707]]

In [153]:
#Normal Distribution
data = np.random.normal(0, 1, (2, 3))
print(data)

[[-0.70950001  0.27934881  0.00828788]
 [-1.10030738 -0.93198939  1.10318745]]

In [154]:
import numpy as np

!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

zsh:1: command not found: gdown

In [155]:
import pandas as pd
data = pd.read_csv('advertising.csv')
print(data)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [156]:
import numpy as np
x = data['TV']
y = data['Sales']

In [157]:
correlation_coefficien = np.corrcoef(x, y)
print(correlation_coefficien)

[[1.         0.90120791]
 [0.90120791 1.        ]]

In [158]:
x = data['Radio']
y = data['Sales']
print(np.corrcoef(x, y))

[[1.        0.3496311]
 [0.3496311 1.       ]]

In [159]:
x = data['Newspaper']
y = data['Sales']
print(np.corrcoef(x, y))

[[1.         0.15796003]
 [0.15796003 1.        ]]

In [160]:
data_corr_coef = data.corr()
print(data_corr_coef)

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [161]:
data.head(5)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [162]:
data.tail(5)

        TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [163]:
data.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [164]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [165]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [166]:
data = pd.read_csv('vi_text_retrieval.csv')
print(data)

             id                                           question  \
0    1570446247  Quang Hải giành được chức vô địch U21 quốc gia...
1    1570445661                   Mỗi hiệp bóng đá kéo dài bao lâu
2    1570382095            Quân đội Hoa Kỳ gồm những lực lượng nào
3    1570382072                                     Ngọc Lan là ai
4    1570382037         Thu Phương từng được những giải thưởng nào
..          ...                                                ...
495  1569486091  Dân số của Sóc Trăng đứng thứ mấy trong khu vự...
496  1569486072  Các nguyên lý toán học của triết học tự nhiên ...
497  1569486003                    Biến đổi khí hậu Trái Đất là gì
498  1569485614     Phanxicô Xaviê Trương Bửu Diệp mất vào năm nào
499  1569485573  Mật độ dân số của vùng trung du và miền núi ph...

                                                  text
0    Năm 2013 , Nguyễn Quang Hải giành chức vô địch...
1    Một trận đấu bóng đá thông thường có hai hiệp ...
2    Quân đội Hoa Kỳ hay Các lực lượng vũ trang Hoa...
3    Ngọc Lan ( 28 tháng 12 năm 1956 - 6 tháng 3 20...
4    Cô được coi là một trong những ca sĩ thuộc thế...
..                                                 ...
495  Sóc Trăng là một tỉnh ven biển thuộc đồng bằng...
496  Đây là những điều cơ bản tiên quyết của cơ học...
497  Biến đổi khí hậu là những biến đổi trong môi t...
498  Phanxicô Xaviê Trương Bửu Diệp ( 1 tháng 1 năm...
499  Vùng trung du miền núi phía bắc , trước năm 19...

[500 rows x 3 columns]

In [167]:
data.iloc[0]

id                                                 1570446247
question    Quang Hải giành được chức vô địch U21 quốc gia...
text        Năm 2013 , Nguyễn Quang Hải giành chức vô địch...
Name: 0, dtype: object

In [168]:
data['text']

0      Năm 2013 , Nguyễn Quang Hải giành chức vô địch...
1      Một trận đấu bóng đá thông thường có hai hiệp ...
2      Quân đội Hoa Kỳ hay Các lực lượng vũ trang Hoa...
3      Ngọc Lan ( 28 tháng 12 năm 1956 - 6 tháng 3 20...
4      Cô được coi là một trong những ca sĩ thuộc thế...
                             ...
495    Sóc Trăng là một tỉnh ven biển thuộc đồng bằng...
496    Đây là những điều cơ bản tiên quyết của cơ học...
497    Biến đổi khí hậu là những biến đổi trong môi t...
498    Phanxicô Xaviê Trương Bửu Diệp ( 1 tháng 1 năm...
499    Vùng trung du miền núi phía bắc , trước năm 19...
Name: text, Length: 500, dtype: str

In [169]:
#Convert to Lower
context = data['text']
context = [doc.lower() for doc in context]
context[:5]

['năm 2013 , nguyễn quang hải giành chức vô địch u21 quốc gia 2013 cùng với đội trẻ hà nội t&t và tạo nên cú sốc khi trở thành cầu thủ 16 tuổi đầu tiên giành được danh hiệu vô địch u21 quốc gia .',
 'một trận đấu bóng đá thông thường có hai hiệp , mỗi hiệp 45 phút với khoảng thời gian 15 phút nghỉ giữa hai hiệp .',
 'quân đội hoa kỳ hay các lực lượng vũ trang hoa kỳ là tổng hợp các lực lượng quân sự thống nhất của hoa kỳ . các lực lượng này gồm có lục quân , hải quân , thuỷ quân lục chiến , không quân và tuần duyên .',
 'ngọc lan ( 28 tháng 12 năm 1956 - 6 tháng 3 2001 ) là một ca sĩ hải ngoại nổi tiếng . không chỉ với giọng hát , cô còn được khán giả đặc biệt yêu mến vì khuôn mặt khả ái và tính cách nhút nhát , khiêm tốn của mình .',
 'cô được coi là một trong những ca sĩ thuộc thế hệ thứ hai của nền nhạc nhẹ việt nam đạt được nhiều giải thưởng nhất .']

In [170]:
tf_idf_vectorizer = TfidfVectorizer(max_features=500)

In [171]:
context_embeded = tf_idf_vectorizer.fit_transform(context)

In [172]:
context_embeded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16098 stored elements and shape (500, 500)>

In [173]:
tf_idf_vectorizer.vocabulary_

{'năm': np.int64(266),
 'nguyễn': np.int64(235),
 'hải': np.int64(151),
 'chức': np.int64(68),
 'vô': np.int64(427),
 'quốc': np.int64(299),
 'gia': np.int64(110),
 'cùng': np.int64(82),
 'với': np.int64(438),
 'đội': np.int64(491),
 'hà': np.int64(142),
 'nội': np.int64(272),
 'và': np.int64(424),
 'tạo': np.int64(399),
 'nên': np.int64(263),
 'khi': np.int64(163),
 'trở': np.int64(382),
 'thành': np.int64(334),
 'cầu': np.int64(88),
 'thủ': np.int64(351),
 'tuổi': np.int64(386),
 'đầu': np.int64(477),
 'tiên': np.int64(355),
 'được': np.int64(470),
 'danh': np.int64(94),
 'hiệu': np.int64(131),
 'một': np.int64(222),
 'trận': np.int64(379),
 'đấu': np.int64(476),
 'bóng': np.int64(37),
 'đá': np.int64(459),
 'thông': np.int64(339),
 'thường': np.int64(341),
 'có': np.int64(79),
 'hai': np.int64(127),
 'hiệp': np.int64(130),
 'khoảng': np.int64(166),
 'thời': np.int64(350),
 'gian': np.int64(112),
 '15': np.int64(6),
 'giữa': np.int64(121),
 'quân': np.int64(296),
 'hoa': np.int64(132),
 'kỳ': np.int64(180),
 'hay': np.int64(128),
 'các': np.int64(75),
 'lực': np.int64(207),
 'lượng': np.int64(199),
 'vũ': np.int64(431),
 'trang': np.int64(362),
 'là': np.int64(191),
 'tổng': np.int64(406),
 'hợp': np.int64(160),
 'sự': np.int64(319),
 'thống': np.int64(348),
 'nhất': np.int64(254),
 'của': np.int64(92),
 'này': np.int64(262),
 'gồm': np.int64(125),
 'lục': np.int64(206),
 'thuỷ': np.int64(333),
 'chiến': np.int64(52),
 'không': np.int64(171),
 'ngọc': np.int64(241),
 'lan': np.int64(183),
 'tháng': np.int64(336),
 '12': np.int64(3),
 'ca': np.int64(49),
 'sĩ': np.int64(310),
 'nổi': np.int64(271),
 'tiếng': np.int64(357),
 'chỉ': np.int64(66),
 'hát': np.int64(147),
 'cô': np.int64(80),
 'còn': np.int64(78),
 'giả': np.int64(118),
 'đặc': np.int64(478),
 'biệt': np.int64(30),
 'mặt': np.int64(221),
 'tính': np.int64(393),
 'cách': np.int64(76),
 'mình': np.int64(216),
 'coi': np.int64(70),
 'trong': np.int64(367),
 'những': np.int64(260),
 'thuộc': np.int64(332),
 'thế': np.int64(345),
 'hệ': np.int64(153),
 'thứ': np.int64(352),
 'nền': np.int64(270),
 'nhạc': np.int64(253),
 'việt': np.int64(422),
 'nam': np.int64(227),
 'nhiều': np.int64(246),
 'giải': np.int64(119),
 'na': np.int64(226),
 'uy': np.int64(415),
 'tên': np.int64(391),
 'chính': np.int64(59),
 'thức': np.int64(353),
 'vương': np.int64(432),
 'theo': np.int64(325),
 'thể': np.int64(346),
 'chế': np.int64(65),
 'chủ': np.int64(67),
 'lập': np.int64(203),
 'tại': np.int64(398),
 'bắc': np.int64(41),
 'âu': np.int64(449),
 'phần': np.int64(286),
 'phía': np.int64(282),
 'tây': np.int64(390),
 'bán': np.int64(34),
 'đảo': np.int64(474),
 'nước': np.int64(268),
 'giáp': np.int64(117),
 'biên': np.int64(25),
 'giới': np.int64(120),
 'nga': np.int64(229),
 'từ': np.int64(410),
 'lớn': np.int64(205),
 'hơn': np.int64(149),
 'rất': np.int64(301),
 'đông': np.int64(466),
 'bà': np.int64(32),
 'thật': np.int64(344),
 'thị': np.int64(347),
 'xuân': np.int64(441),
 'sinh': np.int64(305),
 'ngày': np.int64(237),
 '10': np.int64(1),
 'la': np.int64(182),
 'xã': np.int64(444),
 'văn': np.int64(430),
 'tỉnh': np.int64(403),
 'nay': np.int64(228),
 'quận': np.int64(298),
 'xuất': np.int64(442),
 'đình': np.int64(463),
 'công': np.int64(81),
 'mất': np.int64(220),
 'bố': np.int64(45),
 'tác': np.int64(388),
 'nhỏ': np.int64(259),
 'đến': np.int64(481),
 'trưởng': np.int64(376),
 'đế': np.int64(480),
 'cổ': np.int64(90),
 'chuyển': np.int64(56),
 'tự': np.int64(413),
 'du': np.int64(99),
 'mục': np.int64(224),
 'lịch': np.int64(204),
 'sử': np.int64(318),
 'từng': np.int64(411),
 'tồn': np.int64(404),
 'kỷ': np.int64(181),
 '13': np.int64(4),
 '14': np.int64(5),
 'trên': np.int64(370),
 'vùng': np.int64(429),
 'nguyên': np.int64(234),
 'trung': np.int64(368),
 'cuối': np.int64(73),
 'đã': np.int64(462),
 'dài': np.int64(101),
 'biển': np.int64(28),
 'nhật': np.int64(257),
 'bản': np.int64(39),
 'bao': np.int64(22),
 'rộng': np.int64(302),
 'về': np.int64(435),
 'tiểu': np.int64(360),
 'địa': np.int64(483),
 'ấn': np.int64(499),
 'độ': np.int64(489),
 'cao': np.int64(50),
 'iran': np.int64(161),
 'điểm': np.int64(454),
 'km': np.int64(176),
 '000': np.int64(0),
 'diện': np.int64(97),
 'tích': np.int64(392),
 'lãnh': np.int64(194),
 'thổ': np.int64(349),
 'lên': np.int64(196),
 'tới': np.int64(408),
 'km2': np.int64(177),
 'trị': np.int64(380),
 'triệu': np.int64(366),
 'dân': np.int64(102),
 'hoá': np.int64(136),
 'học': np.int64(155),
 'kim': np.int64(172),
 'loại': np.int64(189),
 'hy': np.int64(141),
 'lạp': np.int64(201),
 'ra': np.int64(300),
 'dương': np.int64(104),
 'liên': np.int64(185),
 'kết': np.int64(179),
 'người': np.int64(240),
 'ta': np.int64(320),
 'cho': np.int64(53),
 'nó': np.int64(264),
 'tương': np.int64(396),
 'như': np.int64(251),
 'điện': np.int64(455),
 'tử': np.int64(412),
 'đất': np.int64(475),
 'phiên': np.int64(277),
 'âm': np.int64(448),
 'cộng': np.int64(91),
 'hoà': np.int64(133),
 'nhân': np.int64(249),
 'gần': np.int64(122),
 'bị': np.int64(44),
 'đoạn': np.int64(457),
 'cực': np.int64(93),
 'vịnh': np.int64(437),
 'bắt': np.int64(42),
 'nghiệp': np.int64(230),
 'trước': np.int64(374),
 'nơi': np.int64(267),
 'làm': np.int64(192),
 'anh': np.int64(19),
 'ký': np.int64(178),
 'đồng': np.int64(487),
 'sau': np.int64(304),
 'đó': np.int64(464),
 'tiền': np.int64(359),
 'đạo': np.int64(472),
 'cũng': np.int64(83),
 'đời': np.int64(493),
 'vận': np.int64(433),
 'hội': np.int64(159),
 'vào': np.int64(426),
 'tổ': np.int64(405),
 'lần': np.int64(202),
 'nguồn': np.int64(236),
 'hiện': np.int64(129),
 'đại': np.int64(471),
 'số': np.int64(315),
 'xếp': np.int64(445),
 'nhưng': np.int64(252),
 'đứng': np.int64(495),
 'hàng': np.int64(144),
 'biến': np.int64(26),
 'mã': np.int64(214),
 'tức': np.int64(409),
 'đơn': np.int64(468),
 'vị': np.int64(436),
 'tôn': np.int64(394),
 'sơn': np.int64(311),
 'chi': np.int64(51),
 'nhà': np.int64(248),
 'mạng': np.int64(219),
 'vai': np.int64(417),
 'trò': np.int64(373),
 'quan': np.int64(293),
 'trọng': np.int64(381),
 'cuộc': np.int64(74),
 'triều': np.int64(364),
 'thanh': np.int64(323),
 'khai': np.int64(162),
 'bảo': np.int64(40),
 'pháp': np.int64(279),
 '21': np.int64(15),
 'đi': np.int64(452),
 'tranh': np.int64(363),
 'mỹ': np.int64(225),
 'đô': np.int64(465),
 'nghệ': np.int64(232),
 'an': np.int64(18),
 'chuyên': np.int64(55),
 'thi': np.int64(326),
 'trí': np.int64(372),
 'bộ': np.int64(47),
 'hoàng': np.int64(135),
 'tuyển': np.int64(385),
 'sân': np.int64(308),
 'bay': np.int64(23),
 'tế': np.int64(402),
 'châu': np.int64(57),
 'cấp': np.int64(86),
 'để': np.int64(482),
 'vụ': np.int64(439),
 'mùa': np.int64(218),
 'ba': np.int64(20),
 'tư': np.int64(395),
 'gọi': np.int64(123),
 'hồi': np.int64(157),
 'giáo': np.int64(116),
 'quyền': np.int64(295),
 'khu': np.int64(167),
 'vực': np.int64(440),
 'chữ': np.int64(69),
 'hán': np.int64(146),
 'phong': np.int64(278),
 'kiến': np.int64(174),
 'hình': np.int64(148),
 'thuật': np.int64(331),
 'truyền': np.int64(369),
 'phát': np.int64(280),
 'triển': np.int64(365),
 'tâm': np.int64(389),
 'sông': np.int64(309),
 'hồng': np.int64(158),
 'miền': np.int64(210),
 'đức': np.int64(494),
 'qua': np.int64(292),
 'kinh': np.int64(173),
 'phải': np.int64(285),
 'nhận': np.int64(255),
 'toàn': np.int64(361),
 'nghĩa': np.int64(231),
 'thực': np.int64(354),
 'hậu': np.int64(152),
 'giang': np.int64(113),
 'bằng': np.int64(43),
 'long': np.int64(188),
 'nằm': np.int64(269),
 'thơ': np.int64(340),
 'giá': np.int64(115),
 'phố': np.int64(289),
 'di': np.int64(95),
 'sản': np.int64(313),
 'ước': np.int64(497),
 '11': np.int64(2),
 'tộc': np.int64(407),
 'yếu': np.int64(446),
 'nhóm': np.int64(250),
 'khác': np.int64(168),
 'phật': np.int64(288),
 'thiên': np.int64(327),
 'chúa': np.int64(60),
 'thuyết': np.int64(330),
 'duy': np.int64(100),
 'linh': np.int64(184),
 '1963': np.int64(9),
 'phan': np.int64(274),
 'huyện': np.int64(140),
 'ông': np.int64(450),
 'sư': np.int64(312),
 'khách': np.int64(169),
 'phẩm': np.int64(287),
 'lê': np.int64(195),
 'hoàn': np.int64(134),
 'thánh': np.int64(337),
 'xây': np.int64(443),
 'dựng': np.int64(109),
 'khoa': np.int64(164),
 'đối': np.int64(486),
 'tỷ': np.int64(414),
 'chất': np.int64(64),
 'đây': np.int64(461),
 'méxico': np.int64(215),
 'ban': np.int64(21),
 'nha': np.int64(243),
 'tuyên': np.int64(384),
 'độc': np.int64(490),
 'chu': np.int64(54),
 'hồ': np.int64(156),
 'hoạt': np.int64(137),
 'động': np.int64(492),
 'quảng': np.int64(297),
 'hành': np.int64(145),
 'niên': np.int64(261),
 '18': np.int64(7),
 'vua': np.int64(423),
 'minh': np.int64(209),
 '30': np.int64(17),
 'sách': np.int64(306),
 'cơ': np.int64(84),
 'phương': np.int64(284),
 'bạc': np.int64(38),
 'nhiên': np.int64(245),
 'vi': np.int64(418),
 'lâm': np.int64(193),
 'biết': np.int64(27),
 'nữ': np.int64(273),
 'diễn': np.int64(96),
 'viên': np.int64(419),
 'hàn': np.int64(143),
 'phim': np.int64(276),
 'võ': np.int64(428),
 'thần': np.int64(343),
 '2016': np.int64(13),
 'the': np.int64(324),
 '2017': np.int64(14),
 'tiếp': np.int64(358),
 'sắc': np.int64(314),
 'chương': np.int64(63),
 'trình': np.int64(371),
 'trường': np.int64(375),
 'đào': np.int64(458),
 'hoặc': np.int64(138),
 'môn': np.int64(217),
 'nhau': np.int64(244),
 'cả': np.int64(85),
 'thái': np.int64(335),
 '20': np.int64(10),
 'ngôi': np.int64(238),
 'đổi': np.int64(488),
 'con': np.int64(71),
 'điều': np.int64(453),
 '22': np.int64(16),
 'do': np.int64(98),
 'thu': np.int64(329),
 'mà': np.int64(211),
 'hạ': np.int64(150),
 'dạng': np.int64(106),
 'phân': np.int64(281),
 'định': np.int64(484),
 'bình': np.int64(36),
 'viết': np.int64(420),
 'tắt': np.int64(401),
 'nhập': np.int64(256),
 'màu': np.int64(212),
 'gốc': np.int64(124),
 'đa': np.int64(451),
 'trần': np.int64(378),
 'thượng': np.int64(342),
 'quy': np.int64(294),
 'chí': np.int64(58),
 'khí': np.int64(170),
 'kiện': np.int64(175),
 'tiêu': np.int64(356),
 'vàng': np.int64(425),
 'vật': np.int64(434),
 'biểu': np.int64(29),
 'đường': np.int64(469),
 'lưu': np.int64(198),
 'chúng': np.int64(61),
 'cung': np.int64(72),
 'liệu': np.int64(187),
 '2015': np.int64(12),
 'đánh': np.int64(460),
 'thiết': np.int64(328),
 'dùng': np.int64(103),
 'lý': np.int64(197),
 'ngôn': np.int64(239),
 'ngữ': np.int64(242),
 'nhằm': np.int64(258),
 'cấu': np.int64(87),
 'mang': np.int64(208),
 'sao': np.int64(303),
 '19': np.int64(8),
 'bài': np.int64(33),
 'đĩa': np.int64(467),
 'việc': np.int64(421),
 'uỷ': np.int64(416),
 'ương': np.int64(496),
 'đảng': np.int64(473),
 'giao': np.int64(114),
 'tướng': np.int64(397),
 'sáng': np.int64(307),
 'dụng': np.int64(108),
 'ngoài': np.int64(233),
 'báo': np.int64(35),
 'sống': np.int64(316),
 'tập': np.int64(400),
 'máy': np.int64(213),
 'nói': np.int64(265),
 'phú': np.int64(283),
 'sở': np.int64(317),
 'mới': np.int64(223),
 'lại': np.int64(200),
 'phủ': np.int64(291),
 'luật': np.int64(190),
 'nhiệm': np.int64(247),
 'brasil': np.int64(31),
 'cái': np.int64(77),
 'đặt': np.int64(479),
 'khoá': np.int64(165),
 'tam': np.int64(321),
 'dẫn': np.int64(107),
 'huy': np.int64(139),
 'gỗ': np.int64(126),
 'phổ': np.int64(290),
 'họ': np.int64(154),
 'chơi': np.int64(62),
 '2011': np.int64(11),
 'tài': np.int64(387),
 'đoàn': np.int64(456),
 'đỏ': np.int64(485),
 'dưới': np.int64(105),
 'ảnh': np.int64(498),
 'giai': np.int64(111),
 'tcn': np.int64(322),
 'bởi': np.int64(48),
 'trấn': np.int64(377),
 'bồ': np.int64(46),
 'trực': np.int64(383),
 'phi': np.int64(275),
 'cố': np.int64(89),
 'tháp': np.int64(338),
 'liêu': np.int64(186),
 'ánh': np.int64(447),
 'bhutan': np.int64(24)}

In [174]:
question = data.iloc[0]['question']
print(question)

Quang Hải giành được chức vô địch U21 quốc gia năm bao nhiêu tuổi

In [175]:
query_embeded = tf_idf_vectorizer.transform([question.lower()])
query_embeded.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.41170748, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.34409734, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.25375103, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.39807499, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.16932766, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.19847826,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40694845, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.47002099, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.18614089, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [176]:
from sklearn.metrics.pairwise import cosine_similarity
consine_scores = cosine_similarity(context_embeded, query_embeded).reshape((-1, ))

consine_scores

array([0.57893894, 0.        , 0.04324174, 0.11867385, 0.0462411 ,
       0.04020499, 0.09262766, 0.07334046, 0.        , 0.10025643,
       0.09711281, 0.10404656, 0.        , 0.11062764, 0.04483115,
       0.08200432, 0.08717163, 0.01513549, 0.02218694, 0.03012534,
       0.        , 0.01060537, 0.01596474, 0.04271932, 0.10404656,
       0.        , 0.07060081, 0.11980622, 0.        , 0.        ,
       0.12800329, 0.01610309, 0.        , 0.05859667, 0.05674335,
       0.        , 0.06027257, 0.07105423, 0.0127644 , 0.0246541 ,
       0.03086477, 0.02730909, 0.07375455, 0.01632256, 0.03539357,
       0.        , 0.05381381, 0.        , 0.03653642, 0.        ,
       0.10216567, 0.08786483, 0.        , 0.03455317, 0.        ,
       0.12924531, 0.02803859, 0.        , 0.03653642, 0.07474625,
       0.07644765, 0.04365014, 0.01421474, 0.        , 0.09518449,
       0.07664112, 0.03549977, 0.10371288, 0.        , 0.        ,
       0.07664112, 0.02238682, 0.03455317, 0.06027257, 0.0860899 ,
       0.01999538, 0.        , 0.01479339, 0.08884735, 0.06870706,
       0.04405439, 0.10092858, 0.04476148, 0.0377045 , 0.07305948,
       0.05983863, 0.02100444, 0.01596474, 0.12392032, 0.01880111,
       0.10371288, 0.02827222, 0.02212394, 0.08012659, 0.01028722,
       0.09933833, 0.04641883, 0.37748767, 0.01479339, 0.01947743,
       0.06358527, 0.09624573, 0.09443548, 0.06366689, 0.0170583 ,
       0.        , 0.06215237, 0.04468228, 0.06193091, 0.06865779,
       0.14142946, 0.05110184, 0.        , 0.01469468, 0.04459742,
       0.10231024, 0.13316207, 0.        , 0.        , 0.0680077 ,
       0.10886311, 0.08775634, 0.01483195, 0.03364028, 0.        ,
       0.03653642, 0.02104722, 0.02540737, 0.03715926, 0.        ,
       0.        , 0.10522961, 0.01190962, 0.01497789, 0.06330194,
       0.        , 0.22672737, 0.00767539, 0.01437902, 0.14161414,
       0.027466  , 0.        , 0.10231024, 0.02547826, 0.04365014,
       0.        , 0.03357984, 0.        , 0.02450395, 0.04845591,
       0.00801681, 0.07459109, 0.06501803, 0.01496211, 0.0245568 ,
       0.        , 0.09932991, 0.        , 0.0542465 , 0.03468627,
       0.00759811, 0.        , 0.0630398 , 0.06501803, 0.03653642,
       0.11719387, 0.0719888 , 0.        , 0.06748806, 0.04170635,
       0.0278731 , 0.01967171, 0.01469468, 0.009425  , 0.03202973,
       0.01189503, 0.03450947, 0.00917266, 0.04578126, 0.03392368,
       0.02831866, 0.        , 0.        , 0.07800017, 0.1764808 ,
       0.02806288, 0.03366979, 0.04191627, 0.03971658, 0.07551878,
       0.01128025, 0.03115445, 0.01793222, 0.05577715, 0.07382317,
       0.01294859, 0.        , 0.08900632, 0.        , 0.01221288,
       0.03278188, 0.07060081, 0.03566201, 0.08060678, 0.09515689,
       0.14837513, 0.05110184, 0.        , 0.05835254, 0.08717163,
       0.04084331, 0.04066467, 0.04170635, 0.01067613, 0.04115938,
       0.        , 0.07925668, 0.02721497, 0.0147646 , 0.02478117,
       0.03988131, 0.        , 0.01873648, 0.07601209, 0.00929884,
       0.12688745, 0.09932991, 0.04846275, 0.07695278, 0.02661482,
       0.02547826, 0.04191627, 0.        , 0.06461753, 0.056362  ,
       0.01350577, 0.01276005, 0.00653004, 0.05703463, 0.0414299 ,
       0.04598629, 0.0127375 , 0.10847277, 0.01600938, 0.02347982,
       0.13582549, 0.02261699, 0.0219552 , 0.        , 0.        ,
       0.04447699, 0.09320759, 0.02806288, 0.04878219, 0.        ,
       0.        , 0.07212559, 0.02116275, 0.09150157, 0.02831866,
       0.09157291, 0.13269477, 0.01408661, 0.03155281, 0.02669134,
       0.        , 0.07298898, 0.11707712, 0.02554586, 0.01067613,
       0.        , 0.01445902, 0.07866721, 0.05819226, 0.        ,
       0.01211423, 0.        , 0.07143755, 0.        , 0.09513614,
       0.01350577, 0.0678853 , 0.02865893, 0.07375455, 0.00825565,
       0.05019775, 0.03304531, 0.11736938, 0.15303693, 0.08012659,
       0.02116275, 0.01655448, 0.03756752, 0.09590379, 0.01617148,
       0.04447699, 0.06360533, 0.        , 0.        , 0.02605828,
       0.06179814, 0.09382357, 0.05457775, 0.10602053, 0.        ,
       0.01420495, 0.07319379, 0.10323548, 0.04614685, 0.        ,
       0.01221288, 0.0199735 , 0.0719888 , 0.03569881, 0.09654089,
       0.08465353, 0.        , 0.01820977, 0.00688815, 0.01401726,
       0.03478547, 0.0826763 , 0.00688815, 0.02331847, 0.08229954,
       0.04094054, 0.        , 0.02423408, 0.        , 0.02562817,
       0.10602053, 0.05596939, 0.        , 0.        , 0.02113756,
       0.01479736, 0.07741861, 0.05899938, 0.0507927 , 0.03459127,
       0.06575524, 0.0127375 , 0.01756991, 0.01199056, 0.06290673,
       0.01734388, 0.03474017, 0.07171121, 0.        , 0.        ,
       0.04963825, 0.09590379, 0.07252316, 0.        , 0.01345845,
       0.08749828, 0.02618625, 0.01689785, 0.051172  , 0.        ,
       0.        , 0.0719888 , 0.        , 0.08620818, 0.01864368,
       0.09665095, 0.1381284 , 0.04094054, 0.12738886, 0.02550026,
       0.01984482, 0.03590078, 0.05486262, 0.01915815, 0.        ,
       0.12738886, 0.08246194, 0.        , 0.01724778, 0.04584852,
       0.03473669, 0.04281783, 0.03232852, 0.09590456, 0.18835355,
       0.        , 0.        , 0.01307984, 0.        , 0.        ,
       0.        , 0.02754893, 0.0719888 , 0.09133147, 0.04124376,
       0.04933401, 0.06302863, 0.06800788, 0.02026372, 0.03473669,
       0.06952234, 0.01681683, 0.0169704 , 0.0790778 , 0.02236159,
       0.22022242, 0.04320708, 0.        , 0.14881429, 0.04534529,
       0.06280515, 0.        , 0.        , 0.07382317, 0.08053858,
       0.01149612, 0.04722911, 0.06800788, 0.06952234, 0.023917  ,
       0.04738374, 0.01755191, 0.13324676, 0.01249289, 0.09730844,
       0.05506757, 0.        , 0.05201998, 0.06559579, 0.02116275,
       0.        , 0.03046559, 0.04094054, 0.0158621 , 0.02907061,
       0.02701324, 0.        , 0.03287115, 0.        , 0.05130744,
       0.24329471, 0.12738886, 0.        , 0.        , 0.01034968,
       0.08351418, 0.05968784, 0.0711708 , 0.0464017 , 0.01320712,
       0.        , 0.08313627, 0.        , 0.02688686, 0.10576863,
       0.01277278, 0.01941973, 0.        , 0.03336069, 0.00973094,
       0.08915531, 0.00973094, 0.        , 0.02614294, 0.        ,
       0.06784656, 0.01855389, 0.0623704 , 0.04024423, 0.00973094,
       0.09803158, 0.0464017 , 0.03723766, 0.        , 0.05951754,
       0.        , 0.        , 0.02584519, 0.04687666, 0.12085542,
       0.08184118, 0.16959262, 0.07429346, 0.01178767, 0.03331537,
       0.        , 0.0496891 , 0.03579282, 0.1499101 , 0.        ,
       0.00693331, 0.        , 0.09887976, 0.        , 0.06755435,
       0.        , 0.02980145, 0.01075441, 0.06755435, 0.0119537 ])

In [177]:
top_d = 5
for idx in consine_scores.argsort()[-top_d:][::-1]:
    print('Score: ',consine_scores[idx])
    print(data.iloc[idx, 2])
    print('______')

Score:  0.5789389362010777
Năm 2013 , Nguyễn Quang Hải giành chức vô địch U21 quốc gia 2013 cùng với đội trẻ Hà Nội T&T và tạo nên cú sốc khi trở thành cầu thủ 16 tuổi đầu tiên giành được danh hiệu vô địch U21 quốc gia .
______
Score:  0.37748766531906297
Bao Công huý là Bao Chửng ( chữ Hán : 包拯 ; 11 tháng 4 năm 999 - 20 tháng 5 năm 1062 ) , tự Hy Nhân . Ngoài ra , ông còn được gọi là Bao Thanh thiên , Bao Đãi chế , Bao Hắc tử , Bao Học sĩ hay Bao Long Đồ .
______
Score:  0.24329470996695696
Khi còn bé , Luffy đã vô tình ăn phải trái ác quỷ do Shanks dành dược từ thuyền địch nên anh đã trở thành người cao su . Tuy ăn phải trái ác quỷ làm cậu không thể bơi , nhưng mong muốn ra biển đặc biệt là ước muốn trở thành Vua Hải tặc và tìm được kho báu One Piece của Luffy vẫn không hề giảm . 10 năm sau từ quê hương là làng Foosha , ở Đảo Dawn thuộc East Blue , Luffy lên dường tìm kiếm đồng đội để lập băng hải tặc cho riêng mình , băng băng Mũ Rơm , hành trình trở thành Hải tặc của Luffy bắt đầu .
______
Score:  0.22672737038492638
Arsenal đã giành được 13 chức vô địch quốc gia , 13 Cúp FA ( kỷ lục ) , 2 Cúp Liên đoàn Anh , 1 Cúp Liên đoàn Thế kỷ , 15 Siêu cúp Anh , 1 Cúp UEFA và 1 Cúp Inter-Cities Fairs . Arsenal là câu lạc bộ có số trận thắng ở cấp cao nhất nhiều thứ hai trong lịch sử bóng đá Anh , và cũng là đội bóng Anh duy nhất cho đến nay vô địch quốc gia với thành tích bất bại qua 38 vòng đấu , nhận biệt danh The Invincibles ( tiếng Việt : " Đội bóng bất bại " ) và giành Cúp vàng Ngoại hạng Anh .
______
Score:  0.22022242040404838
Thành Vatican , tên chính thức : Thành quốc Vatican ( tiếng Ý : " Stato della Città del Vaticano " ; tiếng Latinh : " Status Civitatis Vaticanae " ) là một quốc gia có chủ quyền với lãnh thổ bao gồm một vùng đất có tường bao kín nằm trong lòng thành phố Roma , Ý. Với diện tích khoảng 44 hécta ( 110 mẫu Anh ) , và dân số khoảng 1000 người , khiến Vatican được quốc tế công nhận là thành phố , quốc gia độc lập nhỏ nhất thế giới về góc độ diện tích và dân số .
______

In [ ]:
corr_coef_scores = np.corrcoef(query_embeded.toarray()[0], context_embeded.toarray())
for index in corr_coef_scores[0][1:].argsort()[-top_d:][::-1]:
    print("Scores", corr_coef_scores[0][index])
    print(data.iloc[index, 2])
    print("_______________")

Scores 1.0

KeyError: (np.int64(0), 2)